### PR TITLE
Converted some PCP metrics to count_per_second

### PR DESCRIPTION
**Pull request by kmada97**
changed metrics that said count / sec to count_per_second
Signed-Off-By: Kalyan Mada <kalyan.red.mada@hpe.com>

### CODE REVIEW

**Comment by roclark** [comment]
One thing I see off the bat is with the commit title. It's beyond the 50 character limit for GitHub and has wrapped awkwardly. I would do a short-and-sweet title and maybe use this as your commit details. Remember to, in general, follow the guidelines for commit messages found here: https://chris.beams.io/posts/git-commit/

**Comment by roclark** [comment]
@joehandzik for context, @kmada97 ran into an issue where Prometheus was unable to process a name that ended with "...count / sec", which is why he added this line.

**Review by joehandzik — CHANGES_REQUESTED** [review]
This should probably be count_per_second rather than counts_per_second

**Comment by joehandzik** [comment]
@roclark the purpose makes sense, thanks for the context. This is the sort of thing I figured we might run into occasionally. We'll fix them as we find them. Also agree regarding the title wrapping, it's easy to fix.

**Review by joehandzik — APPROVED** [review]

**Comment by joehandzik** [comment]
@kmada97 Your commit comment still doesn't make any sense. Try to think of a short commit message for that top line that would immediately make it clear what you did. Something like:

"Convert some PCP metrics to count_per_second"

Or something like that. Once you change that, let me know and I'll merge.

**Pull request merged**
